### ISSUE TITLE
display fixtures not used

### ISSUE THREAD

**Issue by BugsBunnyBR** [concretesolutions/requestmatcher#10]
In this [line](https://github.com/concretesolutions/requestmatcher/blob/5686ca1ee1b632fd419fd95d3ae793d49d74e5f0/requestmatcher/src/main/java/br/com/concretesolutions/requestmatcher/RequestMatcherRule.java#L288) is said that, there are some fixtures not used. It could be useful to know which ones.

**Comment by cs-victor-nascimento** [comment]
This is gping to be on the next release thanks to @cleemansen. We will only refactor a bit how we cover the test cases and remove one issue with local tests.

**Comment by cs-victor-nascimento** [comment]
Done. Available on 2.2.0.

Thanks for reporting
