### ISSUE TITLE
Remove use of Android classes

### ISSUE THREAD

**Issue by heitorcolangelo** [concretesolutions/requestmatcher#13]
The library is using some Android classes, like TextUtils.
That way I can't use requestmatcher in unit tests that does not depends on Android classes.

**Comment by cs-victor-nascimento** [comment]
Nice catch :)

Will factor those classes out.

**Comment by cs-victor-nascimento** [comment]
Removed on version 2.2.0. Now local tests of the lib will always run without `Robolectric`.

Thanks :)
