### ISSUE TITLE
Recorded Request Body must be read multiple times

### ISSUE THREAD

**Issue by cleemansen** [concretesolutions/requestmatcher#6]
Hi all,

first of all thanks for that very helpful tool!

I've noticed that there is an issue when you need to get the body of a recorded request multiple times. 

This happens when there are multiple requests in the Set which are equal in Request-Method, Request-Path, Request-Query, Request-Headers but with different Request-Body.
In that situation it is possible that the "wrong" matcher is in front of the correct matcher. Because the "wrong" matcher takes the body of the taken request this body is not any more available for future asserts.

The second issue is that I had a hard time to figure out which matcher did not match because of what reason.

For details please see my pull request...

**Comment by cs-victor-nascimento** [comment]
Fixed in #7
